name: plugboard

services:
  rabbitmq:
    image: rabbitmq:4.0-rc-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - main
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    restart: always

  postgres:
    image: postgres:18rc1-alpine  # TODO: Update to stable version when released
    container_name: postgres
    environment:
      - POSTGRES_USER=plugboard
      - POSTGRES_PASSWORD=plugboard
      - POSTGRES_DB=plugboard
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main
    restart: always

  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: valkey
    command: valkey-server --dir /var/lib/valkey --bind 0.0.0.0 -::1 --protected-mode no
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/var/lib/valkey
    networks:
      - main
    restart: always

networks:
  main:
    driver: bridge

volumes:
  rabbitmq-data:
  postgres-data:
  valkey-data:
