site_name: Plugboard
site_url: https://docs.plugboard.dev
site_description: An event-driven modelling and orchestration framework for simulating complex processes

repo_name: plugboard-dev/plugboard
repo_url: https://github.com/plugboard-dev/plugboard
extra:
  version:
    provider: mike

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          docstring_style: google
          show_source: false
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_symbol_type_method: true
          show_signature_annotations: true
          merge_init_into_class: true
          separate_signature: true

- mike:
    alias_type: symlink
    canonical_version: latest

markdown_extensions:
# Annotations: https://squidfunk.github.io/mkdocs-material/reference/annotations/
- attr_list
- md_in_html
- pymdownx.superfences
# Code blocks: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    dedent_subsections: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
- css/mkdocstrings.css

extra_javascript:
- https://buttons.github.io/buttons.js

theme:
  name: material
  custom_dir: docs/overrides
  features:
  - navigation.tabs
  - content.code.annotate
  - content.code.copy
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

watch:
- mkdocs.yaml
- docs
- plugboard
- README.md
- CONTRIBUTING.md

nav:
- Home: index.md
- Examples:
  - Hello world: examples/001_hello_world/hello-world.md
  - Simple model: examples/002_simple_model/simple-model.md
- API Reference:
  - component: api/component/component.md
  - connector: api/connector/connector.md
  - exceptions: api/exceptions/exceptions.md
  - library: api/library/library.md
  - process: api/process/process.md
  - schemas: api/schemas/schemas.md
  - state: api/state/state.md
  - utils: api/utils/utils.md
- Contributing: contributing.md
