name: Bug report
description: Report an error or unexpected behavior
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug, including a minimal reproducible example (MRE).
        If we cannot reproduce the bug, it is unlikely that we will be able to help you.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version Information
      description: Please paste the output of `plugboard version`
      placeholder: |
        Plugboard version: 0.1.0
        Platform: Linux-6.11.0-1018-azure-x86_64-with-glibc2.39
        Python version: 3.12.3
      render: text
    validations:
      required: true