name: Benchmarks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Benchmark tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install project
        run: uv sync --group test

      - name: Setup benchmarks
        run: |
          echo "BASE_SHA=$(echo ${{ github.event.pull_request.base.sha }} | cut -c1-8)" >> $GITHUB_ENV
          echo "HEAD_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8)" >> $GITHUB_ENV
          echo "PR_COMMENT=$(mktemp)" >> $GITHUB_ENV

      - name: Run benchmarks
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          uv run pytest --benchmark-only --benchmark-save=base

          git checkout ${{ github.event.pull_request.head.sha }}
          uv run pytest --benchmark-only --benchmark-save=branch

      - name: Compare results
        run: |
          uv run pytest-benchmark compare | tee cmp_results

          echo 'Benchmark comparison for [`${{ env.BASE_SHA }}`](${{ github.event.repository.html_url }}/commit/${{ github.event.pull_request.base.sha }}) (base) vs [`${{ env.HEAD_SHA }}`](${{ github.event.repository.html_url }}/commit/${{ github.event.pull_request.head.sha }}) (PR)' >> pr_comment
          echo '```' >> pr_comment
          echo cmp_results >> pr_comment
          echo '```' >> pr_comment
          cat pr_comment > ${{ env.PR_COMMENT }}
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: require('fs').readFileSync('${{ env.PR_COMMENT }}').toString()
            });

