name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

env:
  POETRY_VERSION: '1.8'

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true

  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}

      - name: Install
        run: |
          pip install poetry==$POETRY_VERSION
          poetry install --with docs
      
      # Run all checks, even if some fail
      - name: Ruff linting
        run: poetry run ruff check .
        if: always()

      - name: Ruff formatting
        run: poetry run ruff format --check .
        if: always()

      - name: Type checking
        run: poetry run mypy .
        if: always()

      - name: Tests
        run: poetry run pytest .
        if: always()

      - name: Notebook output cleared
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
        if: always()

      - name: Build docs
        run: poetry run mkdocs build
        if: always()

      - name: Build package
        run: poetry build
        if: always()

